import { supabase } from '../lib/supabase';

export type ToolResult<T=unknown>={tool:string;ok:boolean;data?:T;error?:string};
async function requireUser(){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Authentication required');return user;}
export async function searchCourses(query:string):Promise<ToolResult>{try{await requireUser();const q=query.trim();if(!q)return{tool:'search_courses',ok:false,error:'Search query required'};const{data,error}=await supabase.from('courses').select('*').or(`title.ilike.%${q}%,description.ilike.%${q}%`).limit(10);if(error)throw error;return{tool:'search_courses',ok:true,data};}catch(e:any){return{tool:'search_courses',ok:false,error:e.message||'Course search failed'}}}
export async function searchOpportunities(query=''):Promise<ToolResult>{try{await requireUser();let request=supabase.from('opportunities').select('*').eq('status','open').limit(20);if(query.trim())request=request.or(`title.ilike.%${query.trim()}%,description.ilike.%${query.trim()}%`);const{data,error}=await request;if(error)throw error;return{tool:'search_jobs',ok:true,data};}catch(e:any){return{tool:'search_jobs',ok:false,error:e.message||'Job search failed'}}}
export async function searchScholarships(query=''):Promise<ToolResult>{try{await requireUser();let request=supabase.from('scholarships').select('*').limit(20);if(query.trim())request=request.or(`name.ilike.%${query.trim()}%,description.ilike.%${query.trim()}%`);const{data,error}=await request;if(error)throw error;return{tool:'search_scholarships',ok:true,data};}catch(e:any){return{tool:'search_scholarships',ok:false,error:e.message||'Scholarship search failed'}}}
export async function getMyProfile():Promise<ToolResult>{try{const user=await requireUser();const{data,error}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;return{tool:'get_my_profile',ok:true,data};}catch(e:any){return{tool:'get_my_profile',ok:false,error:e.message||'Profile lookup failed'}}}
export async function getMyLearningProgress():Promise<ToolResult>{try{const user=await requireUser();const{data,error}=await supabase.from('student_progress').select('*').eq('student_id',user.id).limit(100);if(error)throw error;return{tool:'get_student_progress',ok:true,data};}catch(e:any){return{tool:'get_student_progress',ok:false,error:e.message||'Progress lookup failed'}}}
export const MELA_AI_TOOLS={searchCourses,searchOpportunities,searchScholarships,getMyProfile,getMyLearningProgress};
