import React,{useEffect,useRef,useState}from'react';
import {MelaAIChat} from './MelaAIChat';
import {supabase} from '../lib/supabase';
type Msg={id:string;role:'user'|'assistant';content:string;agent?:string;pendingApproval?:boolean};
const suggestions:Record<string,string[]>={student:['Explain my current course','Create a study plan','Find suitable scholarships'],teacher:['Create a lesson plan','Generate a quiz','Analyze student progress'],parent:['Explain my child’s learning progress','Suggest learning activities'],company:['Find suitable candidates','Improve my vacancy','Create a recruitment plan'],admin:['Show AI activity','Analyze platform growth','Review pending approvals']};
export default function MelaAIExperience({role='student'}:{role?:string}){
 const[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const end=useRef<HTMLDivElement>(null);const chat=useRef<MelaAIChat|null>(null);
 useEffect(()=>{let active=true;(async()=>{const{data:{session}}=await supabase.auth.getSession();if(active&&session)chat.current=new MelaAIChat({supabaseUrl:import.meta.env.VITE_SUPABASE_URL,accessToken:session.access_token});})();return()=>{active=false}},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy]);
 const send=async(text=input)=>{const value=text.trim();if(!value||busy)return;setInput('');setError('');setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',content:value}]);setBusy(true);try{let c=chat.current;if(!c){const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Please sign in to use MELA AI.');c=new MelaAIChat({supabaseUrl:import.meta.env.VITE_SUPABASE_URL,accessToken:session.access_token});chat.current=c}const r=await c.send(value);setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',content:r.response||r.error||'No response was returned.',agent:r.agent?.name,pendingApproval:r.requires_approval}])}catch(e:any){setError(e?.message||'MELA AI could not complete the request.')}finally{setBusy(false)}};
 const chips=suggestions[role.toLowerCase()]||suggestions.student;
 return <section className="mela-ai" aria-label="MELA AI"><header className="mela-ai-head"><div><strong>MELA AI</strong><span>Your role-aware MELA assistant</span></div><span className="ai-status">● Ready</span></header><div className="mela-ai-messages">{messages.length===0&&<div className="mela-ai-empty"><h2>How can MELA AI help?</h2><p>I use your authorized MELA data and tools. I do not guess private platform information.</p><div className="mela-ai-chips">{chips.map(s=><button type="button" key={s}onClick={()=>void send(s)}>{s}</button>)}</div></div>}{messages.map(m=><article key={m.id} className={`mela-ai-msg ${m.role}`}><div className="mela-ai-bubble">{m.content}</div>{m.agent&&<small>Agent: {m.agent}{m.pendingApproval?' · Approval required':''}</small>}</article>)}{busy&&<div className="mela-ai-msg assistant"><div className="mela-ai-bubble">MELA AI is working…</div></div>}<div ref={end}/></div>{error&&<div className="mela-ai-error" role="alert">{error}</div>}<form className="mela-ai-input"onSubmit={e=>{e.preventDefault();void send()}}><input value={input}onChange={e=>setInput(e.target.value)}placeholder="Ask MELA AI…"disabled={busy}/><button type="submit"disabled={busy||!input.trim()}>{busy?'Working…':'Send'}</button></form></section>;
}
