import { getMelaAITools, type MelaAIToolName } from './MelaAIToolRegistry';

export type AgentKey='student'|'teacher'|'parent'|'career'|'job'|'scholarship'|'content'|'company'|'marketing'|'growth'|'research'|'strategy'|'sales'|'partnership'|'finance'|'hr'|'operations'|'project_manager'|'product'|'technology'|'qa'|'security'|'analytics'|'support'|'admin';
export type PlanStep={agent:AgentKey;purpose:string;tools:MelaAIToolName[]};
const routes:Record<string,AgentKey>={student:'student',teacher:'teacher',parent:'parent',company:'company',admin:'admin'};
const rules:[RegExp,AgentKey][]=[[/scholarship|scholarships/i,'scholarship'],[/job|vacanc|career|cv|resume|interview/i,'career'],[/lesson|quiz|assignment|exam|teaching/i,'teacher'],[/course|study|learn|academic|subject/i,'student'],[/marketing|campaign|customer acquisition/i,'marketing'],[/growth|retention|churn|conversion/i,'growth'],[/competitor|market research|swot/i,'research'],[/business strategy|pricing|business model/i,'strategy'],[/sales|lead|pipeline/i,'sales'],[/partnership|partner/i,'partnership'],[/revenue|expense|budget|finance/i,'finance'],[/hire|hiring|employee|hr/i,'hr'],[/operation|sop|workflow/i,'operations'],[/project|deadline|blocker/i,'project_manager'],[/product|feature|roadmap/i,'product'],[/bug|architecture|technical|performance/i,'technology'],[/test|regression|qa/i,'qa'],[/security|permission|suspicious/i,'security'],[/analytics|kpi|funnel|metrics/i,'analytics'],[/support|problem|help|issue/i,'support']];
export function selectAgent(message:string,role:string):AgentKey{for(const [pattern,agent] of rules)if(pattern.test(message))return agent;return routes[role.toLowerCase()]||'support'}
export function buildPlan(message:string,role:string):PlanStep[]{const primary=selectAgent(message,role);const tools=getMelaAITools(role);const allowed=new Set(tools.map(t=>t.name));const plan:PlanStep[]=[{agent:primary,purpose:'Handle the primary request',tools:tools.slice(0,5).map(t=>t.name)}];if(/analytics|kpi|metrics|analy[sz]e/i.test(message)&&primary!=='analytics')plan.push({agent:'analytics',purpose:'Analyze measurable data supporting the request',tools:[]});return plan.map(s=>({...s,tools:s.tools.filter(t=>allowed.has(t))})).slice(0,3)}
export function enforcePlan(plan:PlanStep[],maxSteps=6){if(plan.length>maxSteps)throw new Error('AI workflow exceeded the maximum safe execution steps');return plan}
