import React,{useEffect,useRef,useState}from'react';
import { MelaAIChat } from './MelaAIChat';
type Msg={id:string;role:'user'|'assistant';content:string;agent?:string;pendingApproval?:boolean};
const suggestions:Record<string,string[]>={student:['Explain my current course','Create a study plan','Find suitable scholarships'],teacher:['Create a lesson plan','Generate a quiz','Analyze student progress'],parent:['Explain my child’s learning progress','Suggest learning activities'],company:['Find suitable candidates','Improve my vacancy','Create a recruitment plan'],admin:['Show AI activity','Analyze platform growth','Review pending approvals']};
export default function MelaAIExperience({role='student'}:{role?:string}){
 const[messages,setMessages]=useState<Msg[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const end=useRef<HTMLDivElement>(null);const chat=useRef<MelaAIChat|null>(null);
 useEffect(()=>{chat.current=new MelaAIChat();end.current?.scrollIntoView({behavior:'smooth'})},[messages]);
 const send=async(text=input)=>{const value=text.trim();if(!value||busy)return;setInput('');setError('');setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',content:value}]);setBusy(true);try{const r=await chat.current!.send(value,{role});setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',content:r.content,agent:r.agent,pendingApproval:r.pendingApproval}])}catch(e:any){setError(e?.message||'MELA AI could not complete the request.')}finally{setBusy(false)}};
 const chips=suggestions[role.toLowerCase()]||suggestions.student;
 return <section className="mela-ai" aria-label="MELA AI"><header className="mela-ai-head"><div><strong>MELA AI</strong><span>Your role-aware MELA assistant</span></div><span className="ai-status">● Ready</span></header><div className="mela-ai-messages">{messages.length===0&&<div className="mela-ai-empty"><h2>How can MELA AI help?</h2><p>I use your authorized MELA data and tools. I do not guess private platform information.</p><div className="mela-ai-chips">{chips.map(s=><button key={s}onClick={()=>void send(s)}>{s}</button>)}</div></div>}{messages.map(m=><article key={m.id} className={`mela-ai-msg ${m.role}`}><div className="mela-ai-bubble">{m.content}</div>{m.agent&&<small>Agent: {m.agent}{m.pendingApproval?' · Approval required':''}</small>}</article>)}{busy&&<div className="mela-ai-msg assistant"><div className="mela-ai-bubble">MELA AI is working…</div></div>}<div ref={end}/></div>{error&&<div className="mela-ai-error">{error}</div>}<form className="mela-ai-input"onSubmit={e=>{e.preventDefault();void send()}}><input value={input}onChange={e=>setInput(e.target.value)}placeholder="Ask MELA AI…"disabled={busy}/><button disabled={busy||!input.trim()}>{busy?'Working…':'Send'}</button></form></section>;
}
